### PR TITLE
Change version file to more appropriate name

### PR DESCRIPTION
**Pull request by tmarcu**
Signed-off-by: Tudor Marcu tudor.marcu@intel.com

### CODE REVIEW

**Comment by tmarcu** [comment]
Needs to be merged in sync with mixer-tools commit.

**Comment by phmccarty** [comment]
Change looks okay. However, swupd-server also needs the same change.

**Comment by phmccarty** [comment]
@tmarcu: I know we had discussed at some point renaming the /var/lib/update/image directory to be /var/lib/update/chroots instead, so how about making that change now, too? And then LAST_VER could live in /var/lib/update instead, which makes more sense.

Proposed new hierarchy:

```
/var/lib/update/www/ (web content for each build)
/var/lib/update/chroots/ (individual bundle chroots per build + "full" chroot per build)
/var/lib/update/meta/ (the metadata produced by bundle-chroot-builder per build)
/var/lib/update/LAST_VER
/var/lib/update/server.ini
/var/lib/update/groups.ini
```

**Comment by tmarcu** [comment]
@phmccarty  That's totally fine, I think it's trivial and makes sense as long as we push them in at the same time. These happened to be sitting on my branch already before we talked about the extra changes, so they could be updated.

**Comment by tmarcu** [comment]
Merged 629f9406762e72bbceedde18d321521b2cf81a3a.

**Pull request closed without merging**
