### PR TITLE
Don't use os-core chroot as base for other bundles

### PR DESCRIPTION
**Pull request by bryteise**
Currently there is an issue with running yum in docker where the yum db
would become corrupt when attempting to reuse an existing db file under
certain conditons that are not well understood.

In order to avoid this issue, instead of using a copy of the os-core
chroot when building the other chroots, create all chroots from fresh
instead.

This change does have a negative performance impact since yum will be
duplicating installation steps but this change was the most reliable way
to create chroots under docker.

As an aside, skipping the yum install of filesystem as a pre-step was
also looked at but dismissed due to the possibility of permissions
getting set incorrectly when creating the chroots because of yum install
order.

### CODE REVIEW

**Comment by tmarcu** [comment]
It would be nice if this had a -docker flag so we don't get performance loss when running this on not docker, which is the major use case currently.

**Comment by bryteise** [comment]
How much of a performance impact is it on the systems of interest?

**Comment by tmarcu** [comment]
I don't know :) You thought it was enough to mention on the commit message, which makes it seem like it's big enough to look into more.

**Comment by tmarcu** [comment]
@bryteise Is there any chance this could be tested again with overlay2 now that we discovered it fixes a few other issues?

**Comment by tmarcu** [comment]
After quite a bit more testing with overlay2, and with the ovl plugin, I still have had no luck getting the current implementation to work. I think the best solution is to add an environment flag or parameter to pass in so BCB knows it must do things differently for a container.

**Comment by cmarcelo** [comment]
Maybe useful/related: https://github.com/moby/moby/issues/10180#issuecomment-252563599

**Pull request closed without merging**
